# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AndroidNativeCustomRefreshView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'UITableView+FDTemplateLayoutCell'
  pod 'Masonry'
  pod 'MJRefresh'

  # Pods for AndroidNativeCustomRefreshView

  target 'AndroidNativeCustomRefreshView-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AndroidNativeCustomRefreshViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
